name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: install-pug
      run: yarn global add pug-cli
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dst
